<a href="https://colab.research.google.com/github/nithingovindugari/IntrotoQC/blob/main/Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
import random
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize

# #problem3
v1 = np.array([[np.sqrt(3)],[1]])
v2 = np.array([[1],[1]])
inner_result = np.vdot(v1,v2)
print(inner_result)
print(v1.shape)

v3 = np.array([[1j],[1]])
v4 = np.array([[-1j],[1]])
inner_result1 = np.vdot(v3,v4)
print(inner_result1)

v5 = np.array([[1+2j],[1]])
v6 = np.array([[1-1j],[1]])
inner_result2 = np.vdot(v5,v6)
print(inner_result2)

#Problem 4
v1 = np.array([[2],[1]])     
print(v1)
v2 = v1/np.linalg.norm(v1) 
print(v2)

v3 = np.array([[2],[1+1j]])     
print(v3)
v4 = v3/np.linalg.norm(v3) 
print(v4)


#Problem 5.2
v1 = np.array([[3/np.sqrt(2)],[1/np.sqrt(2)]])     
print(v1)
v2 = v1/np.linalg.norm(v1) 
print(v2)

# Problem 5.4
v3 = np.array([[1] , [(2 )]])     
print(v3)
v4 = v3/np.linalg.norm(v3) 
print(v4)

2.732050807568877
(2, 1)
0j
-3j
[[2]
 [1]]
[[0.89442719]
 [0.4472136 ]]
[[2.+0.j]
 [1.+1.j]]
[[0.81649658+0.j        ]
 [0.40824829+0.40824829j]]
[[2.12132034]
 [0.70710678]]
[[0.9486833 ]
 [0.31622777]]
[[1]
 [2]]
[[0.4472136 ]
 [0.89442719]]


In [ ]:
#Lecture_6-Problems
sigmay = np.array([[0, -1j],[1j,0]])
print(sigmay)
eigenvalues,eigenvectors = np.linalg.eig(sigmay)
print(eigenvalues)
print(eigenvectors)


[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[ 1.+0.j -1.+0.j]
[[-0.        -0.70710678j  0.70710678+0.j        ]
 [ 0.70710678+0.j          0.        -0.70710678j]]


In [ ]:
#Lecture_7-Problems
#7.1
sigmay=np.array([[0,-1j],[1j,0]])
print(sigmay)
print(np.matmul(sigmay, sigmay))

#7.2
sigmaz=np.array([[1,0],[0,-1]])
print(sigmaz)
print(np.matmul(sigmaz, sigmaz))

#7.3

sigmayh = np.conjugate(np.transpose(sigmay))
print(sigmayh)

#7.4
zerospin=np.array([[1],[0]])
print(zerospin.shape)
print(np.dot(sigmay,zerospin))

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]
[[ 0.-0.j  0.-1.j]
 [-0.+1.j  0.-0.j]]
(2, 1)
[[0.+0.j]
 [0.+1.j]]


In [ ]:
#Lecture_8-Problems

import numpy as np
sigmax=np.array([[0,1],[1,0]])
print(sigmax)
eigenvalues, eigenvectors=np.linalg.eig(sigmax)
print(eigenvalues)
print(eigenvectors)

#8.4
sigmaxp=np.array([1/np.sqrt(2),1/np.sqrt(2)])
sigmaxn=np.array([1/np.sqrt(2),-1/np.sqrt(2)])
eigenvalues, eigenvectors=np.linalg.eig(sigmax)
print(eigenvalues)
print(eigenvectors)
print(np.dot(sigmaxp,sigmaxp))
print(np.dot(sigmaxn,sigmaxn))





[[0 1]
 [1 0]]
[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
0.9999999999999998
0.9999999999999998


In [ ]:
#Lecture_9-Problems
#9.3
# M=np.array([[1,0],[0,-1]])
sigmax=np.array([[0,1],[1,0]])
sigmay=np.array([[0,-1j],[1j,0]])
sigmaz=np.array([[1,0],[0,-1]])



print(np.linalg.det(sigmax))
print(np.linalg.det(sigmay))
print(np.linalg.det(sigmaz))



-1.0
(-1+0j)
-1.0


In [ ]:
#Lecture_10-Problems

#10.4

import numpy as np
sigmaxn=np.array([1/np.sqrt(2),-1])
sigmaxp=np.array([1/np.sqrt(2),1])
sigmayp=np.array([1/np.sqrt(2),+1j])
sigmayn=np.array([1/np.sqrt(2),-1j])

print(np.matmul(sigmaxn, sigmayn))
print(np.matmul(sigmaxn, sigmayp))
print(np.matmul(sigmaxp, sigmayn))
print(np.matmul(sigmaxp, sigmayp))


(0.4999999999999999+1j)
(0.4999999999999999-1j)
(0.4999999999999999-1j)
(0.4999999999999999+1j)


In [ ]:
#Lecture_11-Problems

#11.4
#proving 11.1
import numpy as np
g=np.array([[0],[1]])
h=np.array([[1/np.sqrt(2)],[1j/np.sqrt(2)]])
print(np.kron(g,h))
print(np.kron(h,g))

# proving 11.2
x = np.kron(h,g)
print(np.kron(g,x))

#proving 11.3
y=np.array([[1],[0]])
z = (g + y)
print(np.kron(z,h))
a = np.kron(z,h)


l = np.kron(g,h)
m = np.kron(y,h)
b = l+m
print(l+m)

if  a.all() == b.all() :
  print(" L.H.S == R.H.S")


[[0.        +0.j        ]
 [0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]]
[[0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.70710678j]]
[[0.        +0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.70710678j]]
[[0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]]
[[0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]]
 L.H.S == R.H.S


In [ ]:
#Lecture_12-Problems

import numpy as np
g=np.array([[1],[0]])
h=np.array([[1j/np.sqrt(2)],[1/np.sqrt(2)]])
print(np.kron(g,h))
print(np.kron(h,g))



[[0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]]
[[0.        +0.70710678j]
 [0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.j        ]]


In [ ]:

#Chapter 15

#15.1
sigmay=np.array([[0,1],[1,0]])   #Not gate and transpose is same for this matrix
print(sigmay)
print(np.matmul(sigmay, sigmay))

#15.2
sigmac=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])   #CNot gate and transpose is same for this matrix
print(sigmac)
print(np.matmul(sigmac, sigmac))

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:

#24.5
#Keywords
#superposition is sup_pos
#amplitude  is amp

#Grovers Algorithm is implemented using standard procedure.
#Steps followed in books are implemented and tried to create classical grovers algorithm in different style

plots = []

# Putting all qubits in superposition using hadamard gate
def  sup_pos(qubits):
    states = []
    total_states = int(math.pow(2,qubits))
    amp = 1/math.sqrt(total_states)  
    for _ in range(0,total_states):
        states.append(amp)
    return states

# phase flip inverts the states amplitude
def grover_diffusion(states):
    average = sum(states)/len(states)
    for i in range(0,len(states)):
        states[i] = (average-states[i]) + average         #inversion about mean
    return states

#oracle to implement phase inversion
def oracle(states,datalist,key):
    for i in range(0,int(len(datalist))):
        if datalist[i] == key:
            states[i] *= -1                    #phase inversion
    return states



#classical main grover search function 
def grover_search(qubits,datalist,key):
    states = sup_pos(qubits)
    num_iterations  = math.ceil(math.sqrt(math.pow(2,qubits)))        #iterations
    probability_states = []
    for _ in range(0,num_iterations):
        states = oracle(states,datalist,key)
        states = grover_diffusion(states)
        probability_states = [states[i]*states[i] for i in range(0,len(states))]
        plots.append(probability_states)
    return probability_states


def grover(datalist,key):
    size_datalist = len(datalist)
    qubits_needed = math.ceil(math.log(size_datalist,2))
    paddings_required = int(math.pow(2,qubits_needed) - size_datalist)
    #required if the number of data items is not a power of 2.
    for _ in range(0,paddings_required):
         datalist.append(0)
    grover_search(qubits_needed,datalist,key)
    
datalist = random.sample(range(1, 100), 64)
grover(datalist,32)
print(datalist)
print("plots showing the change in probabilities of items after every grover's iteration :")
result ={}
iteration = 1
for plot in plots:
    for i in range(len(plot)):
        result[datalist[i]] = plot[i]
    print("----------------------------------------------------------------------------------------------------------")
    print("Iteration ",iteration," :")
    plt.bar(result.keys(), result.values(),color='b') 
    plt.ylabel("Probability")
    plt.xlabel("Items")  
    plt.show()
    iteration +=1
    print("----------------------------------------------------------------------------------------------------------")




In [ ]:
#25.7

# from sympy.abc import w
N = int(input("Enter a value", ))
w = pow(np.e,1j/2)

matrix=[] 
row=[] 
for i in range(N): #total row is 3
    row=[] 
    for j in range(N): #total column is 3      
        row.append((w)** (i*j) )
        #  row.append( pow(np.e,1j/N) )
    matrix.append(row) #add fully defined column into the row
print( matrix )

Enter a value9
[[(1+0j), (1+0j), (1+0j), (1+0j), (1+0j), (1+0j), (1+0j), (1+0j), (1+0j)], [(1+0j), (0.8775825618903728+0.479425538604203j), (0.5403023058681398+0.8414709848078965j), (0.07073720166770298+0.9974949866040546j), (-0.4161468365471423+0.9092974268256818j), (-0.8011436155469337+0.5984721441039567j), (-0.9899924966004455+0.1411200080598674j), (-0.9364566872907966-0.3507832276896198j), (-0.6536436208636122-0.7568024953079282j)], [(1+0j), (0.5403023058681398+0.8414709848078965j), (-0.4161468365471423+0.9092974268256818j), (-0.9899924966004455+0.1411200080598674j), (-0.6536436208636122-0.7568024953079282j), (0.283662185463226-0.9589242746631387j), (0.9601702866503661-0.2794154981989263j), (0.753902254343305+0.656986598718789j), (-0.14550003380861315+0.9893582466233821j)], [(1+0j), (0.07073720166770298+0.9974949866040546j), (-0.9899924966004455+0.1411200080598674j), (-0.21079579943077997-0.9775301176650972j), (0.9601702866503661-0.2794154981989263j), (0.34663531783502627+0.9379999

In [ ]:
pow(np.e,1j/2)

(0.8775825618903728+0.479425538604203j)

In [ ]:
# Shors simplified algorithm in python but cant handle big prime numbers

# gcf is calculated
def get_gcf(a, b):
    while a != b:
        if a > b:
            a -= b
        elif b > a:
            b -= a
    return a

# I have used below integers as a in our text book we can add any number of numbers

# 12 is not suitable a so i have used incrementation to get better a

Randomint = [8, 10, 12]

for g in Randomint:  
  N = 63
  done = False
  p = 0
  p_values = []
  while not done:
    p += 1
    r = g**p % N
    if g**p % N == 1:
        print(g, p)
        p_values.append(p)
    if len(p_values) >= 1:
        p = p_values[0]
        if p_values[0] % 2 != 0:
            g += 1
            p = 0
            p_values = []
        else:
            x = g**(p/2)+1
            y = g**(p/2)-1
            a = int(get_gcf(N, x))
            b = int(get_gcf(N, y))
            if a == 1 or b == 1:
                g += 1
                p = 0
                p_values = []
            else:
                print(g, p, a, b)
                done = True
    if p > 500:
        g += 1
        p = 0
        p_values = []

  print(a, "x", b, "=", N)

8 2
8 2 9 7
9 x 7 = 63
10 6
10 6 7 9
7 x 9 = 63
13 6
13 6 7 9
7 x 9 = 63
